# Generated by Django 2.2 on 2020-12-20 09:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_bookmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookmarks',
            new_name='Bookmark',
        ),
    ]
